#!/bin/bash

chmod -R 750 "/Library/Application Support/JAMF/ReEnroller"

if [ -e /private/var/root/Library/Preferences/com.jamf.pse.ReEnroller.plist ];then
    rm /private/var/root/Library/Preferences/com.jamf.pse.ReEnroller.plist
fi
